### ISSUE TITLE
Android app QmlBarcodeReader crashes after 2 secs 

### ISSUE THREAD

**Issue by micccaaa** [scytheStudio/SCodes#26]
Output Error in Debug Mode (build with Qt 6.5.0 armeabi-v7a Kit and latest SCodes - software, on Desktop Qt Kit everything is ok)

isHandlerType=false this: DecorView@be48b76[QtActivity]
I ViewRootImpl@284cb5f[QtActivity]: ViewPostIme pointer 1
I MSHandlerLifeCycle: isMultiSplitHandlerRequested: windowingMode=1 isFullscreen=true isPopOver=false isHidden=false skipActivityType=false isHandlerType=false this: DecorView@be48b76[QtActivity]
W Qt A11Y : AccessibilityEvent with empty description
W libQmlBarcodeReader_armeabi-v7a.so: **Qt has caught an exception thrown from an event handler. Throwing**
W libQmlBarcodeReader_armeabi-v7a.so: exceptions from an event handler is not supported in Qt.
W libQmlBarcodeReader_armeabi-v7a.so: You must not let any exception whatsoever propagate through Qt code.
F libc    : /buildbot/src/android/ndk-r25-release/toolchain/llvm-project/libcxx/../../../toolchain/llvm-project/libcxxabi/src/abort_message.cpp:72: abort_message: assertion "terminating with uncaught exception of type std::out_of_range: Requested row is outside the image" failed
12:11:54: 

"com.scythestudio.qmlbarcodereader" beendet.
12:11:54: Das Debuggen von  "-qmljsdebugger=port:57142,block,services:DebugMessages,QmlDebugger,V8Debugger,QmlInspector,DebugTranslation" wurde beendet.

Can you please fix that?

**Comment by jhay06** [comment]
did you fix the issue ? i think the project was abandoned

**Comment by radkoder** [comment]
I can only suspect what the problem was from this log output, probably the same cause as this issue:
[](https://github.com/scytheStudio/SCodes/issues/29)

There was other [issue](https://github.com/scytheStudio/SCodes/issues/31) with camera finding which exhibited the same exception, so maybe it's the same thing.

I've overhauled the camera code for qt6 so that this kind of thing shouldn't happen now.
