### ISSUE TITLE
Qt/QML 6 version

### ISSUE THREAD

**Issue by hackebike** [scytheStudio/SCodes#5]
I am trying to recompile for Qt/QML 6 and it does not compile as other packages have been removed from Qt 6, like Andorid Extras.

Any chance a porting to Qt 6?

**Comment by scytheStudio** [comment]
Thanks for noticing. Definitely, we need to adjust the wrapper to Qt 6.

**Comment by ApiTracer** [comment]
Hello, can I help you to porting SCodes to Qt 6 ?

**Comment by scytheStudio** [comment]
Hi @ApiTracer, currently with Qt 6.2 the main missing module - Qt Multimedia exists. So the only problem should be the fact that Android Extras are missing. What would be your idea to deal with this problem? 

I think that for now android extras could be just skipped and method SBarcodeGenerator could have an `#ifdef` to check if version of Qt is < 6. If so then permissions should be checked, otherwise no.

**Comment by ApiTracer** [comment]
Ok, for now Qt Multimedia is not yet available as binary.
I will wait for it and test this.

**Comment by EndrII** [comment]
any news about port this library to qt6 ?

**Comment by MichaelHeiser** [comment]
Are there any news on porting to Qt 6.2? This is really a great library!

**Comment by radkoder** [comment]
Qt6 version was added some time ago, closing this issue as resolved
